image: docker:latest

services:
    - docker:19.03.0-dind

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: 'overlay2'
    DOCKER_TLS_CERTDIR: '' # obscure issue
    DOCKER_HOST: tcp://docker:2375

before_script:
    - docker info

test:
    stage: test
    script:
        - apk add --no-cache make
        - make ci-test
    artifacts:
        paths:
            - out/tests